<a href="https://colab.research.google.com/github/kartik2627/Ann_project/blob/main/ANN_project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot


In [ ]:
sentence =['the glass of water','the glass of milk','I am good buy','I am good Developer','understand the meaning']
sentence

['the glass of water',
 'the glass of milk',
 'I am good buy',
 'I am good Developer',
 'understand the meaning']

In [ ]:
voc_size = 1000
for i in sentence:
    print(one_hot(i,voc_size))

[830, 313, 505, 77]
[830, 313, 505, 529]
[751, 360, 1, 792]
[751, 360, 1, 199]
[786, 830, 47]


In [ ]:
one_hot_repr = [one_hot(words,voc_size)for words in sentence]
one_hot_repr

[[830, 313, 505, 77],
 [830, 313, 505, 529],
 [751, 360, 1, 792],
 [751, 360, 1, 199],
 [786, 830, 47]]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 830 313 505  77]
 [  0   0   0   0 830 313 505 529]
 [  0   0   0   0 751 360   1 792]
 [  0   0   0   0 751 360   1 199]
 [  0   0   0   0   0 786 830  47]]


In [ ]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step


array([[[-0.03097506, -0.0226678 , -0.03336058, -0.04905628,
          0.01852641, -0.04057593,  0.03176903,  0.0298509 ,
          0.03332621,  0.00607848],
        [-0.03097506, -0.0226678 , -0.03336058, -0.04905628,
          0.01852641, -0.04057593,  0.03176903,  0.0298509 ,
          0.03332621,  0.00607848],
        [-0.03097506, -0.0226678 , -0.03336058, -0.04905628,
          0.01852641, -0.04057593,  0.03176903,  0.0298509 ,
          0.03332621,  0.00607848],
        [-0.03097506, -0.0226678 , -0.03336058, -0.04905628,
          0.01852641, -0.04057593,  0.03176903,  0.0298509 ,
          0.03332621,  0.00607848],
        [ 0.04334069,  0.04144125, -0.02407857, -0.04660672,
         -0.03614321,  0.04750271,  0.00083437,  0.02113967,
          0.00489318,  0.00684176],
        [-0.01815374,  0.04318548, -0.03217219,  0.01078875,
          0.00713845, -0.03652934,  0.03469895,  0.01893904,
         -0.0044025 , -0.0123135 ],
        [ 0.04023408, -0.0230131 , -0.04754892,  0.0